version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: licensing-api
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: gunicorn -b 0.0.0.0:5000 app:app --timeout 120
    volumes:
      - ./backend/json_rules:/app/backend/json_rules
      - ./backend/chroma_db:/app/backend/chroma_db

  nginx:
    image: nginx:alpine
    container_name: licensing-nginx
    restart: always
    volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
          - ./frontend:/usr/share/nginx/html:ro
          - ./certbot/certbot/conf:/etc/letsencrypt
          - ./certbot/certbot/www:/var/www/certbot
          - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: licensing-certbot
    volumes:
      - ./certbot/certbot/conf:/etc/letsencrypt
      - ./certbot/certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait $${!}; done"